name: Chartlink Automation

on:
  schedule:
    # Runs every day from 9:15 AM to 12:00 PM every 15 minutes
    - cron: "15 3-6 * * *"  # (UTC timezone)

  workflow_dispatch: # Allows manual trigger if needed

jobs:
  run-chartlink:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automation Script
        run: python chartlink_automation.py
